2022-08-21 22:37:21,567 INFO    Thread-2 (_run_job):2614 [wandb_setup.py:_flush():76] Configure stats pid to 2614
2022-08-21 22:37:21,568 INFO    Thread-2 (_run_job):2614 [wandb_setup.py:_flush():76] Loading settings from /home/codespace/.config/wandb/settings
2022-08-21 22:37:21,568 INFO    Thread-2 (_run_job):2614 [wandb_setup.py:_flush():76] Loading settings from wandb/settings
2022-08-21 22:37:21,568 INFO    Thread-2 (_run_job):2614 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'entity': 'raihaan123', 'project': 'PINNs', 'root_dir': '/workspaces/UROP-Notes', 'sweep_id': 'jy42uwvz', 'run_id': 'tgm5d3qd', 'sweep_param_path': '/workspaces/UROP-Notes/wandb/sweep-jy42uwvz/config-tgm5d3qd.yaml'}
2022-08-21 22:37:21,568 INFO    Thread-2 (_run_job):2614 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'src/runner.py', 'program': '/workspaces/UROP-Notes/src/runner.py'}
2022-08-21 22:37:21,568 INFO    Thread-2 (_run_job):2614 [wandb_init.py:_log_setup():461] Logging user logs to /workspaces/UROP-Notes/wandb/run-20220821_223721-tgm5d3qd/logs/debug.log
2022-08-21 22:37:21,568 INFO    Thread-2 (_run_job):2614 [wandb_init.py:_log_setup():462] Logging internal logs to /workspaces/UROP-Notes/wandb/run-20220821_223721-tgm5d3qd/logs/debug-internal.log
2022-08-21 22:37:21,568 INFO    Thread-2 (_run_job):2614 [wandb_init.py:init():495] calling init triggers
2022-08-21 22:37:21,568 INFO    Thread-2 (_run_job):2614 [wandb_init.py:init():498] wandb.init called with sweep_config: {'depth': 48, 'height': 23, 'num_domain': 600}
config: {}
2022-08-21 22:37:21,568 INFO    Thread-2 (_run_job):2614 [wandb_init.py:init():548] starting backend
2022-08-21 22:37:21,568 INFO    Thread-2 (_run_job):2614 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-21 22:37:21,597 INFO    Thread-2 (_run_job):2614 [backend.py:ensure_launched():217] starting backend process...
2022-08-21 22:37:21,599 INFO    Thread-2 (_run_job):2614 [backend.py:ensure_launched():222] started backend process with pid: 2775
2022-08-21 22:37:21,600 INFO    Thread-2 (_run_job):2614 [wandb_init.py:init():558] backend started and connected
2022-08-21 22:37:21,606 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_config_callback():1131] config_cb None None {'depth': 48, 'height': 23, 'num_domain': 600}
2022-08-21 22:37:21,609 INFO    Thread-2 (_run_job):2614 [wandb_init.py:init():634] updated telemetry
2022-08-21 22:37:21,615 INFO    Thread-2 (_run_job):2614 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-08-21 22:37:22,645 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_on_init():1919] communicating current version
2022-08-21 22:37:22,680 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_on_init():1923] got version response upgrade_message: "wandb version 0.13.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-08-21 22:37:22,680 INFO    Thread-2 (_run_job):2614 [wandb_init.py:init():700] starting run threads in backend
2022-08-21 22:37:22,772 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_console_start():1893] atexit reg
2022-08-21 22:37:22,773 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.REDIRECT
2022-08-21 22:37:22,773 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_redirect():1771] Redirecting console.
2022-08-21 22:37:22,773 ERROR   Thread-2 (_run_job):2614 [wandb_run.py:_redirect():1830] Failed to redirect.
Traceback (most recent call last):
  File "/opt/python/3.10.4/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1823, in _redirect
    out_redir.install()
  File "/opt/python/3.10.4/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 702, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/opt/python/3.10.4/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 652, in add_fd
    self._register()
  File "/opt/python/3.10.4/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 637, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/opt/python/3.10.4/lib/python3.10/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
2022-08-21 22:37:22,795 INFO    Thread-2 (_run_job):2614 [wandb_init.py:init():732] run started, returning control to user process
2022-08-21 22:38:13,841 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_finish():1680] finishing run raihaan123/PINNs/tgm5d3qd
2022-08-21 22:38:13,842 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 0
2022-08-21 22:38:13,846 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_restore():1834] restore
2022-08-21 22:38:13,850 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 4011
  total_bytes: 4011
}

2022-08-21 22:38:14,029 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 4011
  total_bytes: 4011
}

2022-08-21 22:38:14,690 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 4011
  total_bytes: 7081
}

2022-08-21 22:38:14,792 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 4011
  total_bytes: 7081
}

2022-08-21 22:38:14,894 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 7081
  total_bytes: 7081
}

2022-08-21 22:38:14,996 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 7081
  total_bytes: 7081
}

2022-08-21 22:38:15,098 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 7081
  total_bytes: 7081
}

2022-08-21 22:38:15,201 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 7081
  total_bytes: 7081
}

2022-08-21 22:38:15,303 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 7081
  total_bytes: 7081
}

2022-08-21 22:38:15,405 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 7081
  total_bytes: 7081
}

2022-08-21 22:38:15,829 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 7081
  total_bytes: 7081
}

2022-08-21 22:38:16,195 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 7081
  total_bytes: 7081
}
local_info {
}

2022-08-21 22:38:17,353 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_footer_history_summary_info():3099] rendering history
2022-08-21 22:38:17,353 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_footer_history_summary_info():3131] rendering summary
2022-08-21 22:38:17,357 INFO    Thread-2 (_run_job):2614 [wandb_run.py:_footer_sync_info():3055] logging synced files
